// Package webassets contains the production croc web client embedded into the
// Go binary.
package webassets

import (
	"embed"
	"io/fs"
)

//go:generate npm --prefix ../../web run embed

// embedded contains files generated by `npm run embed` in the web directory.
//
//go:embed dist
var embedded embed.FS

// Files returns the root of the embedded production client.
func Files() fs.FS {
	files, err := fs.Sub(embedded, "dist")
	if err != nil {
		panic(err)
	}
	return files
}
