# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/schollz/croc
%global goipath         github.com/schollz/croc/v11
Version:                11.5.2

%gometa -L -f

Name:           croc
Release:        %autorelease
Summary:        Easily and securely send things from one computer to another

# Detected with go-vendor-tools 0.13.0; explicit mappings are in Source2.
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND CC-BY-4.0 AND ISC AND MIT AND Zlib
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml
Patch0:         completions.patch
Patch1:         package-update.patch

BuildRequires:  go-vendor-tools
BuildRequires:  golang >= 1.27
BuildRequires:  bash-completion
BuildRequires:  zsh
Requires:       ca-certificates
Source3:        croc.1

%description
croc is a tool that allows any two computers to simply and securely transfer
files and folders.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%patch -P0 -p1
%patch -P1 -p1
export GOTOOLCHAIN=local

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
export GOTOOLCHAIN=local
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/croc %{goipath}

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

install -Dpm0644 %{SOURCE3} %{buildroot}%{_mandir}/man1/croc.1
install -Dpm0644 src/install/bash_autocomplete \
                 %{buildroot}%{bash_completions_dir}/croc
cp src/install/zsh_autocomplete _croc
install -Dpm0644 _croc \
                 %{buildroot}%{zsh_completions_dir}/_croc
%{gobuilddir}/bin/croc generate-fish-completion > croc.fish
install -Dpm0644 croc.fish %{buildroot}%{_datadir}/fish/vendor_completions.d/croc.fish

%check
export GOTOOLCHAIN=local
%go_vendor_license_check -c %{S:2}
%if %{with check}
skip="TestPublicIP"
for test in $skip \
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gotest ./...
%endif

%files -f %{go_vendor_license_filelist}
%doc THIRD_PARTY_NOTICES.md
%doc README.md src/install/default.txt
%{_bindir}/croc
%{bash_completions_dir}/croc
%{zsh_completions_dir}/_croc
%{_mandir}/man1/croc.1*
%{_datadir}/fish/vendor_completions.d/croc.fish

%changelog
%autochangelog
