name: Publish to Winget
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: schollz.croc
          installers-regex: '_Windows-\w+\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
